### PR TITLE
Build a Roman Numeral Converter

### PR DESCRIPTION
**Pull request by royajamal**
"https://github.com/royajamal/Roman-Numeral-Converter/assets/168343975/57203f13-efc3-40a4-9623-595b38e465c4"

Use this Roman numeral converter to convert numbers from 1 to 3,999,999 into Roman numerals. Or input a Roman numeral to get its regular Arabic number value which is the same for English values.

Roman numerals are a number system developed in ancient Rome where letters represent numbers. The modern use of Roman numerals involves the letters I, V, X, L, C, D, and M.

To convert Roman numerals greater than 3,999 use the table below for converter inputs. Use a leading underline character to input Roman numerals with an overline. A line over a Roman numeral means it is multiplied by 1,000.
In this project i added
HTML file
CSS file
Linters
JavaScript file
README file

### CODE REVIEW

**Comment by shogof** [comment]
Hi @royajamal,

Wow, you did an excellent job! 👏

**Status: Approved** ✅

**Optional:**
- Include a screenshot of your project in your readme file. 🖼️
- Aim for clear and descriptive comment names in your code. 💬

Keep up the great work! 🌟"

**Comment by royajamal** [comment]
@ahzamir
hello teacher! I hope doing well .please take moment to review my project.

**Review by ahzamir — CHANGES_REQUESTED** [review]
### Hi @royajamal 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Your README.md file live demo is not showing up please solve it:
  - Copy the below code and paste it on your README.md file demo section

```
![Demo](https://github.com/royajamal/Roman-Numeral-Converter/assets/96838030/68287ea1-8d28-4f49-afd0-dc74d50d8095)
```

- Make your design responsive

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

AlmostThereReachGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
❌Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by royajamal** [comment]
@ahzamir 
Thank you from your feedback. Now all things fixed please check it.

**Comment by ahzamir** [comment]
@royajamal 

- Still your page scrolls horizontally in mobile version. Your page should not scroll horizontally check your elements sizing and fix it

**Comment by ahzamir** [comment]
@royajamal 

- Well done your README is now clean just solve the above issue and request for a re-review.

**Comment by royajamal** [comment]
@ahzamir 
Thanks form your feedback.Now all requirements done please check it.

**Review by ahzamir — APPROVED** [review]
### Hi @royajamal 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
